### ISSUE TITLE
Update text in Learn About Confluence page

### ISSUE THREAD

**Issue by mgarciaclosas** [episphere/confluence#110]
The Confluence project is developing a large research resource to uncover breast cancer genetics through genome-wide association studies (GWAS) in diverse populations. 

Broad scientific aims include:
- To discover susceptibility loci and advance knowledge of etiology of breast cancer overall and by subtypes.
- To develop polygenic risk scores and integrate them with known risk factors for personalized risk assessment for breast cancer overall and by subtypes. 
- To discover loci for breast cancer prognosis, long-term survival, response to treatment, and second breast cancer. 

The Confluence project will harmonize existing genome-wide genotyping data from about 150,000 cases and 200,000 controls and double it by generating new genotypes from at least 150,000 additional breast cancer cases and 100,000 controls, for a total of at least 300,000 cases and 300,000 controls of different ancestries. Confluence will also harmonize risk factor, pathology, treatment, toxicities and survival data across studies. Genotyping and harmonization of data is expected to be completed in 2022.

The table below shows the current number of cases and controls from different participating consortia/studies. Numbers are updated regularly.

**Comment by bhaumik55231** [comment]
Text modification is completed!
