### ISSUE TITLE
Another Tab for Data Request

### ISSUE THREAD

**Issue by geetajoshi2019** [episphere/confluence#12]
Add one more tab for Data Request.

This will be disabled for now until we have a backend to handle the system.

**Comment by geetajoshi2019** [comment]
Bhaumik has created a Tab for "Data Request" - with Coming Soon note. Maybe we will get additional input to create and support backend.

**Comment by mgarciaclosas** [comment]
@bhaumik55231 - please close this and any non-active issues to make it easier to track - thank you !
