### ISSUE TITLE
Edits to text above Concept form

### ISSUE THREAD

**Issue by tahearn** [episphere/confluence#154]
Please replace text above the Concept form with the below: 

Please fill out the form below. This will be reviewed by the Data Access Coordination Committees (DACC) of the consortia participating in Confluence. A description of the data access request process and individual consortia DACC guidelines can be viewed here (TO DO, insert link to page with information on the separate DACCs ). Access to data for approved concepts will only be given to investigators listed below, each of whose Institutions will need to sign data transfer agreements with the data coordinating centers that are governing the requested data.

**Comment by bkop-ds** [comment]
Complete, ready for merge.
