### ISSUE TITLE
Concept Form - Genetic Data Requested

### ISSUE THREAD

**Issue by tahearn** [episphere/confluence#155]
In the section asking about specific variants, please replace the text to read: 

If specific variants are being requested, please complete and attach the following manifest (download the manifest template here). Please use build 38 to denote variants.  

**Note we will need to create manifest template to download. The template should be a csv with the column headings: Chromosome, Position, and rsid **

**Comment by bkop-ds** [comment]
Complete, ready for merge. Still need to create manifest template for download (will create separate issue) and need to discuss how these files get uploaded and to where.
