### ISSUE TITLE
Email button for data coordinating center contacts

### ISSUE THREAD

**Issue by tahearn** [episphere/confluence#160]
Here are the emails for the contacts at the consortia data coordinating centers. This is for the button that needs to be added to the Auth Table.

BCAC & CIMBA: Manjeet Bolla, mkh39@medschl.cam.ac.uk
LAGENO: Xiaosong Huang, xjahuang@ucdavis.edu   &   Valentina Andrea Zavala Cordero, vzavala@ucdavis.edu
MERGE: Ralph Santos, r.santos@qub.ac.uk
AABCG: Guochong Jia, guochong.jia@vumc.org
C-NCI: thomas ahearn, thomas.ahearn@nih.gov

**Comment by bkop-ds** [comment]
completed, ready for merge
