### ISSUE TITLE
DACC Chair Page information

### ISSUE THREAD

**Issue by tahearn** [episphere/confluence#161]
The attached slide is a mock up of the DACC Chairs page that needs to be added to the About Confluence page. As we discussed this should be a separate tab from the "Participating Consortium" page. NOTE, this should only be accessible to people after they login to the platform

[Participating.Consortium.Data.Access.Coordinating.Committee.DACC.pptx](https://github.com/episphere/confluence/files/11103284/Participating.Consortium.Data.Access.Coordinating.Committee.DACC.pptx)

**Comment by bkop-ds** [comment]
Completed, ready for merge
