### ISSUE TITLE
Update to Confluence concept - Authorship Requirements

### ISSUE THREAD

**Issue by tahearn** [episphere/confluence#174]
We should add the following text to the authorship requirements section of the concept, with the check box below the text for the submitter to acknowledge they accept these requirements:

"It is expected that manuscripts will be co-led across multiple contributing groups and consortia. Authorship for cross-consortia manuscripts using individual-level data or unpublished summary data will be proposed by lead investigators at the time of concept submission to the DACCs, who will need to approve the proposed authorship. It is anticipated that Recipient will propose authorships in the form of one of these alternatives: 

-	Group(s) authorship with each group/consortium listed in the authorship byline. Contributions of the writing group and other authors will be noted in the contributions section of the manuscript. Authors will be PubMed searchable. 
 or
-	Named authors including co-first and co-last positions when appropriate. It is expected that manuscripts with named authors will include 2-4 authors per study, plus other contributors to data generation and analyses. 

A “hybrid authorship model” that includes some named authors in the author byline that are PubMed searchable,   while other authors are not listed in the author byline and are not PubMed searchable will not be acceptable. The corresponding author of the manuscript is responsible for contacting journals of interest to learn about their authorship guidelines early in the process of writing the manuscript to confirm the journal's guidelines are compatible with the preferred authorship of the Confluence writing group."

**Comment by bkop-ds** [comment]
@tahearn Should this be at the very end of the form where we ask them to confirm they agree to comply with Confluence authorship requirements? Or should it be closer to the top?

**Comment by bkop-ds** [comment]
Make as adjustable window pop up.

**Comment by bkop-ds** [comment]
This has been updated, curious if we should do a clickable information button instead, but the scroll over is working.
