### ISSUE TITLE
Add text to concept form

### ISSUE THREAD

**Issue by tahearn** [episphere/confluence#177]
In section 2. "Phenotype data requested" please update the text to read, "
"All data requests will be provided access to the Confluence core variables. Please select the category of variables being requested. All variables within the category will be provided. [see the data dictionary] (https://episphere.github.io/confluence/#data_exploration/dictionary) for a description of the variables in each category." 

It might be good to eventually create popup windows when you hoover over the variable category name that shows what variables are included in the category.

**Comment by bkop-ds** [comment]
Completed
