### ISSUE TITLE
Assign issues

### ISSUE THREAD

**Issue by mgarciaclosas** [episphere/confluence#28]
@bhaumik55231 I cannot assign issues on github - can you give me permision

**Comment by bhaumik55231** [comment]
@mgarciaclosas It looks like your invitation is still pending. You will have to click on the link you had received in your email associated with Github.

![image](https://user-images.githubusercontent.com/26577910/78289402-26ca8100-74f0-11ea-9873-e53fa6ce8ebe.png)

**Comment by mgarciaclosas** [comment]
@bhaumik55231 - can you resend invitation? I cannot find it

**Comment by bhaumik55231** [comment]
@mgarciaclosas I have sent you a new invite. Please check your spam folder in-case you don't find it in the inbox.

**Comment by mgarciaclosas** [comment]
got it !
