### ISSUE TITLE
Montse Portal

### ISSUE THREAD

**Issue by jonasalmeida** [episphere/confluence#3]
Create a data portal that matches Montse's [GDC](https://portal.gdc.cancer.gov) inspired UI.

**Comment by jonasalmeida** [comment]
root domain, [episphere.github.io/confluence](https://episphere.github.io/confluence), freed. Prototype dashboard moved as per [#2](https://github.com/episphere/confluence/issues/2) to [episphere.github.io/confluence/proto.html](https://episphere.github.io/confluence/proto.html) for reference (please keep it there).

**Comment by geetajoshi2019** [comment]
Per 7/17/Meeting we can close issues that we have completed. Seems like this issue has been addressed by Jonas - thus closing this. Upon Cambridge Review-feedback additional issue list will be created
