### ISSUE TITLE
Confluence App Icon

### ISSUE THREAD

**Issue by mgarciaclosas** [episphere/confluence#32]
The App icon looks like a black square on the ipad or iphone - can we change to show the confluence logo with the dark pink color as in the site ?

**Comment by mgarciaclosas** [comment]
@bhaumik55231  can the icon be fixed ? do you need anything from us ?

**Comment by bhaumik55231** [comment]
Done.

**Comment by mgarciaclosas** [comment]
The App icon looks good but I cannot see the logo image on the landing page when I log in with my iphone (shows a box with. text as a place holder but no logo) - I can see it with from my computer but not iphone

**Comment by mgarciaclosas** [comment]
this is also a problem on my ipad, and I cannot log in from either the ipad or iphone, and I cannot see the circles plot either

**Comment by mgarciaclosas** [comment]
@bhaumik55231 tagging you since this issue was closed
