### ISSUE TITLE
Need to add SSC members to Landing 

### ISSUE THREAD

**Issue by tahearn** [episphere/confluence#39]
We need to add the SSC members to the About section on the landing page
Attached is a slide with the SSC members

[Confluence Scientific Steering Committee.pptx](https://github.com/episphere/confluence/files/4512603/Confluence.Scientific.Steering.Committee.pptx)

**Comment by mgarciaclosas** [comment]
The members of the SSC need to be added under Contacts - 

Please replace:
Principal Investigator
Dr. Montserrat Garcia-Closas
Division of Cancer Epidemiology and Genetics, National Cancer Institute

by

Scientific Steering Committee
with membership below -please use this file for the membership that includes more information than the powerpoint Tom sent 
[Confluence SSC.xlsx](https://github.com/episphere/confluence/files/4512924/Confluence.SSC.xlsx)
