### ISSUE TITLE
Missingness plot II 

### ISSUE THREAD

**Issue by mgarciaclosas** [episphere/confluence#44]
**Rename:**
Missingness statistics -> Subset statistics
No set -> All Subjects
All set -> Complete set

**Definitions [can these be added somewhere?]:**
Subset statistics: This plot shows the number of subjects with data available on variables selected on the bottom left panel. You can filter the numbers shown by case-control status and study by selecting filters on the top left panel.
All Subjects: all subjects in the set with data on any of the selected variables 
Complete set: number of subjects with data on all selected variables
Top bars: number of subjects with data on each of the selected variable (irrespective of the others)
Side bars: number of subjects with data on a combination 2 or more selected variables

**Remove the following variables:**
studyType
exclusion
contrType

**Side Bars:**
the bars with only one dot are redundant with the top bars - the can be removed.

**Comment by bhaumik55231** [comment]
Hi @lorenasandoval88 Could you please remove **studyType**, **exclusion** and **contrType** columns from the [dummy data](https://nih.app.box.com/file/653087731560)

**Comment by lorenasandoval88** [comment]
removed!
