### ISSUE TITLE
ER status is missingness plot

### ISSUE THREAD

**Issue by mgarciaclosas** [episphere/confluence#45]
@lorenasandoval88 ER status variable can only be defined for cases - at the moment it looks like there is data on ER status for 11,536 subjects, only 3,913 of these are cases. When clicking controls, ER status should be missing for everyone. This seems to be a problem with the way the missing variable is defined.

**Comment by lorenasandoval88** [comment]
Yes, the NAs for controls were counted as data available. Now, the 888s and NAs are counted as missing in ER.https://nih.app.box.com/file/682539973716
