### ISSUE TITLE
Subset statistics

### ISSUE THREAD

**Issue by mgarciaclosas** [episphere/confluence#50]
- Can we add brief title to subset statistics (on top of the plot) to make it more clear?:
"Number of subjects with data on combinations of selected variables"

- The ethnicityClass variable is not very informative as a missing/present variable, we will ultimately have ethnicity from everyone on based on genetic testing.  We should remove it from the variable selection, and add it a as a filter variable so that people can see the numbers for specific racial/ethnic subgroups. @lorenasandoval88 this will require updating the code to generate the statistics.

**Comment by lorenasandoval88** [comment]
Turning ethnicityClass to a filter variable gives this output. 

![image](https://user-images.githubusercontent.com/43822820/87048772-25cd7d80-c1ca-11ea-8f95-e532dfaf047e.png)

**Comment by lorenasandoval88** [comment]
I removed ethnicityClass_Don't know. Here is the file:
 https://nih.app.box.com/file/653087731560
