### ISSUE TITLE
Select/unselect all for each Consortia

### ISSUE THREAD

**Issue by lorenasandoval88** [episphere/confluence#52]
@bhaumik55231 Can you please add a select/unselect all option either by clicking the consortia name or by adding check boxes right below them? And can we please change the numbers when hovering to show ###,### without the k?
![image](https://user-images.githubusercontent.com/43822820/87986315-f7de1800-caaa-11ea-9d19-021f94a77db9.png)

**Comment by bhaumik55231** [comment]
Done!
