### ISSUE TITLE
Missingness stats add EthnicityClass as a filter variable and change order

### ISSUE THREAD

**Issue by lorenasandoval88** [episphere/confluence#53]
@bhaumik55231 Can you please add Ethnicity Class as a filter option and order the selector variables like this?
"Age"
"Sex"
"Family history"
"Fhscore"
"ER status index"

let me know if you need me to change the columns in the csv file. Thank you. 
![image](https://user-images.githubusercontent.com/43822820/87987126-18f33880-caac-11ea-86bb-5cc603497544.png)

**Comment by bhaumik55231** [comment]
Done!
