### ISSUE TITLE
select study and submit

### ISSUE THREAD

**Issue by lorenasandoval88** [episphere/confluence#55]
@bhaumik55231 Can we change the wording from "submit" to "run QAQC" or "continue" here? Jean mentioned it gave her the impression the data was being submitted in that step.  Then, can we please change the "continue" that is in the next step to "submit"? 
![image](https://user-images.githubusercontent.com/43822820/89230275-fafbfc80-d5b0-11ea-93bf-6b0adaf556cf.png)

Thank you.

Lorena

**Comment by bhaumik55231** [comment]
Done
