### ISSUE TITLE
Core Data Upload Errors

### ISSUE THREAD

**Issue by szschem** [episphere/confluence#56]
I got a couple unexpected errors when I tried uploading test Core data.  

This error seem inconsistent with the dictionary I am using (version 1.1 16 April 2020):
   Validity error! 1746 invalid value(s) found in "AgeInt" column.
   Invalid value(s) : undefined , 888

I'm not sure how to handle the following errors:
   Validity error! 4037 invalid value(s) found in "SubStudy" column.
   Invalid value(s) : PEGEN , PROMIS
   Validity error! 4037 invalid value(s) found in "Fhscore" column.
   Invalid value(s) : blank

SubStudy has to be a numeric indicator? If we don't have Fhscore what should the value be?

I also had to rename Genotyping_chip to ConfluenceChip.

**Comment by lorenasandoval88** [comment]
Updated "Genotyping_chip"
